enum SidebarItem {
  resultados,
  fundamentos,
    estructura,
    variables,
    entradaSalida,
    operadoresAsignacion,
    operadoresRelacionales,
  condicionales,
    ifElse,
    tiposIf,
    switchCase,
  ciclos,
    ciclosWhile,
    ciclosDoWhile,
    ciclosFor,
    equivalenciaWhile,
}
